Update scripts and PKGBUILDs

diff --git a/archlinux-PKGBUILDs/clean-chroot-manager-git/d.diff b/archlinux-PKGBUILDs/clean-chroot-manager-git/d.diff
--- a/archlinux-PKGBUILDs/clean-chroot-manager-git/d.diff
+++ b/archlinux-PKGBUILDs/clean-chroot-manager-git/d.diff
@@ -1,8 +1,8 @@
 diff --git a/common/clean-chroot-manager32.in b/common/clean-chroot-manager32.in
-index b0369f4..d0e679a 100644
+index b0369f4..1d531c0 100644
 --- a/common/clean-chroot-manager32.in
 +++ b/common/clean-chroot-manager32.in
-@@ -129,45 +129,68 @@ check2() {
+@@ -129,45 +129,69 @@ check2() {
  }
  
  build() {
@@ -18,6 +18,7 @@ index b0369f4..d0e679a 100644
 +	else
 +		# if not cleaning chroot, clean build 'startdir' of working chroot
 +		[[ -d $WORKINGPATH/startdir ]] && rm -rf $WORKINGPATH/startdir/* > /dev/null
++		shift
 +	fi
 +	if [[ ! -z "$RUNNAMCAP" ]]; then
 +		option="$option -n"
@@ -35,7 +36,7 @@ index b0369f4..d0e679a 100644
 -
 -	# stop here if build fails
 -	[[ $? -gt 0 ]] && exit 1
-+	makechrootpkg $option -u -r $CHROOTPATH32 || exit 1     # stop here if build fails
++	makechrootpkg $option -u -r $CHROOTPATH32 -- $* || exit 1     # stop here if build fails
  
  	# if this is the first time package has been successfully built
  	# then append the local repo to the chroot's pacman.conf
@@ -85,16 +86,17 @@ index b0369f4..d0e679a 100644
  
  	# The rm statement above can return 1 if the file to remove is not found,
  	# causing the function to return a non-zero error code even if everything
-@@ -279,7 +302,7 @@ case "$1" in
+@@ -279,7 +303,8 @@ case "$1" in
  			mesg=
  			create
  		fi
 -		build
-+		build $2
++		shift
++		build $*
  		;;
  	u)
  		check2 && update
-@@ -294,6 +317,7 @@ case "$1" in
+@@ -294,6 +319,7 @@ case "$1" in
  		echo
  		echo -e ${BOLD}" --- BUILDING ---"${ALL_OFF}
  		echo -e ${BOLD}" s) Run makepkg in clean chroot"${ALL_OFF}
@@ -103,10 +105,10 @@ index b0369f4..d0e679a 100644
  		echo -e ${BOLD}" --- MISCELLANEOUS ---"${ALL_OFF}
  		echo -e ${BOLD}" l) List local repo in chroot (packages you build)"${ALL_OFF}
 diff --git a/common/clean-chroot-manager64.in b/common/clean-chroot-manager64.in
-index dc6509f..0a7253b 100644
+index dc6509f..0881168 100644
 --- a/common/clean-chroot-manager64.in
 +++ b/common/clean-chroot-manager64.in
-@@ -140,46 +140,68 @@ check2() {
+@@ -140,46 +140,69 @@ check2() {
  }
  
  build() {
@@ -122,6 +124,7 @@ index dc6509f..0a7253b 100644
 +	else
 +		# if not cleaning chroot, clean build 'startdir' of working chroot
 +		[[ -d $WORKINGPATH/startdir ]] && rm -rf $WORKINGPATH/startdir/* > /dev/null
++		shift
 +	fi
 +	if [[ ! -z "$RUNNAMCAP" ]]; then
 +		option="$option -n"
@@ -139,7 +142,7 @@ index dc6509f..0a7253b 100644
 -
 -	# stop here if build fails
 -	[[ $? -gt 0 ]] && exit 1
-+	makechrootpkg $option -u -r $CHROOTPATH64 || exit 1     # stop here if build fails
++	makechrootpkg $option -u -r $CHROOTPATH64 -- $* || exit 1     # stop here if build fails
  
  	# if this is the first time package has been successfully built
  	# then append the local repo to the chroot's pacman.conf
@@ -190,16 +193,17 @@ index dc6509f..0a7253b 100644
  
  	# The rm statement above can return 1 if the file to remove is not found,
  	# causing the function to return a non-zero error code even if everything
-@@ -323,7 +345,7 @@ case "$1" in
+@@ -323,7 +346,8 @@ case "$1" in
  			mesg=
  			create
  		fi
 -			build
-+		build $2
++		shift
++		build $*
  		;;
  	u)
  		check2 && update
-@@ -339,6 +361,7 @@ case "$1" in
+@@ -339,6 +363,7 @@ case "$1" in
  		echo
  		echo -e ${BOLD}" --- BUILDING ---"${ALL_OFF}
  		echo -e ${BOLD}" s) Run makepkg in clean chroot"${ALL_OFF}
